version: '3'
services:
  demo:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
  db:
    image: mysql:5.6
    container_name: zetta-mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=zetta
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql